### ISSUE TITLE
Desktop Entry Name should not include "(Flatpak)"

### ISSUE THREAD

**Issue by deadmeu** [flathub/la.ogri.strongbox#7]
The [desktop entry](https://raw.githubusercontent.com/ogri-la/strongbox-flatpak/7.1.0/strongbox.desktop) currently appends `(Flatpak)` to the Name value. This should be removed as the Name entry should just be the name of the program `Strongbox` and the package format should left out of it.

**Comment by torkus** [comment]
hey @deadmeu , thanks for opening a ticket and sorry for the long delay - I didn't see it! Bug reports are best opened against the main project repo: https://github.com/ogri-la/strongbox

I'll add this to the next release

**Comment by torkus** [comment]
Fixed: https://github.com/ogri-la/strongbox-flatpak/commit/e22e0d744f033c0f563edc6bfbf7c87b27882b72

I anticipate doing a release this weekend (2024-09-07).

Thanks again!
